version: '3.4'
services:
  msv-pedidos:
    image: uniliva/msv-pedidos
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "9056:80" 
    command: mvn spring-boot:run
    networks:
      - univendas-network
networks:
    univendas-network:
        driver: bridge